apiVersion: v1
kind: Service
metadata:
  name: redispack
  labels:
    app: redispack
spec:
  type: LoadBalancer
  ports:
    # the port that this service should serve on
  - port: 8443
    name: ui
    targetPort: 8443
  - port: 8001
    name: sentinal
    targetPort: 8001
  selector:
    app: rp
    role: ui
