apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: redispack
spec:
  volumeClaimTemplates:
  - metadata:
      name: redispack-pv-storage
      annotations:
        volume.alpha.kubernetes.io/storage-class: gce-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      persistentVolumeReclaimPolicy: Recycle
      resources:
        requests:
          storage: 1Gi
  serviceName: redispack-headless
  replicas: 3
  template:
    metadata:
      labels:
        app: rp
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - rp
            topologyKey: kubernetes.io/hostname
      containers:
      - name: redispack
        image: gcr.io/proj-1-1097/rlec-k8s:4.5.0-18.1
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 2
            memory: 4096Mi
        ports:
        - containerPort: 8001
        - containerPort: 8443
        securityContext:
          capabilities:
            add:
               - SYS_RESOURCE
        volumeMounts:
          - mountPath: "/opt/redispack-k8s"
            name: redispack-pv-storage
        env:
          - name: K8S_ORCHASTRATED_DEPLOYMENT
            value: "yes"
          - name: JOIN_HOSTNAME
            value: redispack-0.redispack-headless
          - name: PERSISTANCE_PATH
            value: /opt/redispack-k8s
          - name: BOOTSTRAP_CLUSTER_FQDN
            value: mycluster.k8s
          - name: BOOTSTRAP_USERNAME
            value: demo@redislabs.com
          - name: BOOTSTRAP_PASSWORD
            value: "123456"
          - name: BOOTSTRAP_DMC_THREADS
            value: "10"
          - name: BOOTSTRAP_ACTION
            value: create_cluster
          - name: BOOTSTRAP_LICENSE
            value: "----- LICENSE START -----\\nFz1ZUy0Ykfh1wOwAfpeR/bb5XuRy1eZ7cLRqNFu/ydy+U2KdznDH07sNhy/7\\n5hD08jzklED44pUGuqkgLNfVjYZNVToXRwc+UWm8+zAFqoMkDdegKEBsO5mg\\nn5TGZdSVap8RRCoUTbNLP28lZfJaPXrO45u75vOmsHooyxanuApX/unNGlqp\\nEz4EbV3LAlqCOYlixlgei0iN7IUj0A8+mzN2/M809f+TTEAX7XdJl8Yn7/Z3\\nlpAs/XCjuq10Vvnxv/DPQ0qSAeNRIn07Z5m+OMZFRECNuA6C6inatGGQwhvU\\nCA6WmanmjJkQ18Jflt57hB9yFMJs6UTB4IGFNdmSAQ==\\n----- LICENSE END -----\\n"
