apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: redispack
spec:
  volumeClaimTemplates:
  - metadata:
      name: redispack-pv-storage
      annotations:
        volume.alpha.kubernetes.io/storage-class: gce-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
  serviceName: redispack-headless
  replicas: 2
  template:
    metadata:
      labels:
        app: rp
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - rp
            topologyKey: kubernetes.io/hostname
      containers:
      - name: redispack
        image: redislabs/kuber:4.5.0-18.1
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 2
            memory: 4096Mi
        ports:
        - containerPort: 8001
        - containerPort: 8443
        securityContext:
          capabilities:
            add:
               - SYS_RESOURCE
        volumeMounts:
          - mountPath: "/opt/redispack-k8s"
            name: redispack-pv-storage
        env:
          - name: K8S_ORCHASTRATED_DEPLOYMENT
            value: "yes"
          - name: JOIN_HOSTNAME
            value: redispack-0.redispack-headless
          - name: PERSISTANCE_PATH
            value: /opt/redispack-k8s
          - name: BOOTSTRAP_CLUSTER_FQDN
            value: mycluster.k8s
          - name: BOOTSTRAP_USERNAME
            value: "cihan@redislabs.com"
          - name: BOOTSTRAP_PASSWORD
            value: "redislabs123"
          - name: BOOTSTRAP_DMC_THREADS
            value: "10"
          - name: BOOTSTRAP_ACTION
            value: create_cluster
          - name: BOOTSTRAP_LICENSE
            value: ""
